### ISSUE TITLE
Misalignment museum location - moved

### ISSUE THREAD

**Issue by mcint** [simonw/museums#39]
The misalignment museum moved to out in front of Chase Stadium. I'm not sure how long their deal to stay there lasts. Might be nice to email them to ask, and ask for updates if/when the move again.

https://github.com/simonw/museums/blob/891715247b668ff236f454595fa2cda3f407c814/museums.yaml#L2986

**Comment by simonw** [comment]
Thanks, good call. Updated here: 47fcd2e65fa0a828a61dd6d58b542bae8fdbfadf

**Comment by simonw** [comment]
Deployed: https://www.niche-museums.com/110
