### ISSUE TITLE
Figure out how to accept submissions

### ISSUE THREAD

**Issue by simonw** [simonw/museums#4]
Originally I had intended to accept submissions, but over the past few weeks I've really enjoyed writing my own editorialized captions and using photos I've taken on the site (e.g. https://www.niche-museums.com/browse/museums/43)

But... now I'm getting offers of submissions! https://twitter.com/davidnunez/status/1199424444541751297 and https://twitter.com/brycem/status/1199415935263625216 for example.

I want both. I want to be able to keep my personal "museums I've been to" vibe going, but I also want to collect tips from other people (so when I'm traveling the "Use my location" button can show me places people have suggested).

Need to figure out the neatest way to combine tips from other people with my own personal notes on niche museums that I've visited and loved.

**Comment by simonw** [comment]
My current leading option: start a new YAML file called `tips.yaml` and accept pull requests to it. It can use the same structure as `museums.yaml`.

**Comment by simonw** [comment]
I think I'll skip the issue of photos for tips for the moment - handling those properly will require accepting uploads somewhere, tracking licensing and credits and so forth.

**Comment by amoeba** [comment]
Just my 2c:

> I want to be able to keep my personal "museums I've been to" vibe going

Is great and I think you're right on the money going this direction. Along this line, if you do want contributions, suggesting people only submit niche museums they have actually been to seems fair and probably better than not.

As for how to contribute, `tips.yml` would work great for me. Using GitHub Issue Templates might also work and could be easier than merging numerous PRs to `tips.yml`.

As for how to differentiate museums you've been to versus those that have been contributed, I think allowing the user to toggle between `Simon's | Contributed | All` in the user interface would feel natural and easy to understand.

**Comment by simonw** [comment]
Oops, that commit should not have closed this ticket.

**Comment by aslakr** [comment]
Are you going to add the museums from your Google Maps list <https://goo.gl/maps/riHoUmrXofMAUEDW9>?

**Comment by bobwhitelock** [comment]
@simonw Did you decide to accept contributions in the end?
